### ISSUE TITLE
Add support for Android platform

### ISSUE THREAD

**Issue by nikeorever** [JakeWharton/confundus#5]
Hi, Jake, does this library have plans to support Android in the future?

**Comment by JakeWharton** [comment]
Sure. Shouldn't be that hard to add.

**Comment by nikeorever** [comment]
Looking forward to it, the emergence of **confundus** will allow me to abandon the ugly **not-null assertion operator(!!)**.

**Comment by nikeorever** [comment]
Some time ago, I accidentally added **confundus** to the Android project, but only applied Gradle Plugin (**com.jakewharton.confundus**) without using its API (**unsafeCast**), and the project can be built normally. Until **kapt** was applied, an exception occurred in the build.

The error message is as follows:
**Failed Gradle tasks**: kaptGenerateStubsDebugKotlin
**Stacktrace**:
```
Caused by: java.lang.ClassCastException: org.jetbrains.kotlin.codegen.SignatureCollectingClassBuilderFactory$SignatureCollectingClassBuilder cannot be cast to org.jetbrains.kotlin.codegen.OriginCollectingClassBuilderFactory$OriginCollectingClassBuilder
	at org.jetbrains.kotlin.codegen.OriginCollectingClassBuilderFactory.asBytes(OriginCollectingClassBuilderFactory.kt:62)
	at org.jetbrains.kotlin.codegen.DelegatingClassBuilderFactory.asBytes(DelegatingClassBuilderFactory.kt:36)
```
